# NumPy

https://docs.scipy.org/doc/numpy-1.10.0/reference/ufuncs.html

NumPy arrays are the main way we will use Numpy throughput the course.

Numpy arrays essentially come in two flavors: vectors and matrices.

Vectors are strictly 1D arrays and matrices are 2D (but you should note a matrix can still have only one row or one column)

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [1]:
import numpy as np

### 1D array

In [4]:
arr = np.array(my_list) # list converted to array

In [5]:
arr

array([1, 2, 3])

### 2D array

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(my_mat)

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Builtin functions of numpy to create an array

In [8]:
# bulitin array range function (similar to python range function), returns only integers
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
# builtin function to create array of 1
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
# bulitin function to create 0 vector array
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5)) # 5x5 matrix with all zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3)) # 2x3 matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# builtin function to create evenly spaced points from given range with number of points to display
# 0 ---> starting point
# 5 ---> ending point
# 10 ---> points to display

np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.linspace(0,20,100)

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [17]:
# create identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random Function

In [18]:
# 1D array of random numbers from 0 to 1
np.random.rand(5)

array([0.63891627, 0.85943424, 0.68995159, 0.19096115, 0.87174853])

In [19]:
# 2D array of random numbers from 0 to 1
np.random.rand(3,3)

array([[0.74335816, 0.82815708, 0.51757359],
       [0.12768916, 0.80442842, 0.087202  ],
       [0.39217689, 0.62718296, 0.96804091]])

In [20]:
# randn is used to return numbers from standard normal distribution around 0
# 1D
np.random.randn(2)

array([-0.82997356,  0.01495334])

In [21]:
# 2D
np.random.randn(4,4)

array([[ 2.05338927e-01,  1.60601625e+00,  2.64043414e-02,
         1.92219431e+00],
       [-1.84154150e-01,  9.74344033e-01,  2.92115540e+00,
         3.47758359e-01],
       [ 2.68296527e-01,  2.39783501e-03,  1.45089562e+00,
         1.23644623e-01],
       [-6.80128047e-01, -2.14444114e+00, -1.11464354e-01,
        -6.05403178e-01]])

In [22]:
# random integers between range (low, high)
np.random.randint(1,100)

98

In [23]:
# multiple random integers
np.random.randint(1,100,10)

array([76, 63, 15, 30, 77, 32, 13, 68,  8, 32])

<br>

### Reshape

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
# here, only if arr is having same number of elements after reshape then only it will reshape it
# total size of new arrary must be unchanged
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
# arr.reshape(5,10)
# this throws an error

### Max, Min, and Index of number

In [28]:
ranarr = np.random.randint(0,50,10)

In [29]:
ranarr

array([25, 31, 18,  7, 12, 17, 17, 29,  3, 46])

In [30]:
# max
ranarr.max()

46

In [31]:
# min
ranarr.min()

3

In [32]:
# index of max value
ranarr.argmax()

9

In [33]:
# index of min value
ranarr.argmin()

8

### shape of array

In [34]:
arr.shape

(25,)

In [35]:
ranarr.shape

(10,)

In [36]:
arr.reshape(5,5).shape

(5, 5)

### Data Type

In [37]:
arr.dtype

dtype('int32')

In [38]:
ranarr.dtype

dtype('int32')

### if you dont want to write the whole format for any function then just directly import it and use it

In [39]:
from numpy.random import randint

In [40]:
randint(2,10)

5

In [41]:
randint(10,25,5)

array([24, 10, 13, 15, 17])

<br>

<br>

# NumPy Indexing and Selection

In [42]:
arr = np.arange(0,11)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# indexing

arr[2]

2

In [45]:
# slicing

arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [47]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [48]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
# value assigning to multiple places using slicing
# broadcast
arr[0:5] = 100

In [50]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
slice_arr = arr[0:5]
slice_arr

array([0, 1, 2, 3, 4])

In [54]:
slice_arr[:] = 99

In [55]:
slice_arr

array([99, 99, 99, 99, 99])

In [56]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

Note : this also changes the original array when broadcasting, because slice_arr is not a copy but a view of an array

to avoid this you need to copy the array first using copy function

In [57]:
arr_copy = arr.copy()

In [58]:
arr_copy[:] = 100

In [59]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [60]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [61]:
# indexing in 2D array
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [62]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [63]:
# grabbing row
arr_2d[1]

array([20, 25, 30])

In [64]:
# grabbing column
arr_2d[:,1]

array([10, 25, 40])

In [65]:
arr_2d[:,0]

array([ 5, 20, 35])

In [66]:
# grabbing element
arr_2d[1][2]

30

In [67]:
# grabbing element (alternate method)
arr_2d[2,0]

35

In [68]:
# top right corner 2x2 matrix
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [69]:
# top left
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [70]:
# bottom left
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [71]:
# bottom right
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

### conditional selection

In [72]:
arr = np.arange(1,11)

In [73]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
bool_arr = arr>5

In [75]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [76]:
# only return vlues with boolean True
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [77]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [78]:
arr[arr<3]

array([1, 2])

<br>

<br>

In [79]:
arr_2d = np.arange(50).reshape(5,10)

In [80]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [81]:
'''
13 14
23 24
'''
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [82]:
'''
25 26
35 36
'''
arr_2d[2:4,5:7]

array([[25, 26],
       [35, 36]])

<br>

<br>

<hr>

# NumPy Operations

* Array with Array

* Array with Scalars

* Universal Array Function

In [83]:
arr = np.arange(0,11)

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
# element by element basis
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [86]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [88]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [89]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [90]:
arr / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [92]:
arr - 50

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40])

In [93]:
# in mathematics 0/0 (division by 0) is not allowed, or any number divide by 0 is not allowed
# in array it will return NaN (Null) (for 0/0), or infinity (for any nymber / 0) Value with invalid value encountered in true_divide warning

arr / arr

C:\Users\HP\AppData\Local\Temp\ipykernel_8716\2503252850.py:4: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [94]:
1/arr

C:\Users\HP\AppData\Local\Temp\ipykernel_8716\255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [95]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

### universal array funtions

In [96]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [97]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [98]:
np.max(arr)

10

In [99]:
arr.max()

10

In [100]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [101]:
np.log(arr)

C:\Users\HP\AppData\Local\Temp\ipykernel_8716\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

### sum of values in array

In [2]:
arr = np.arange(10,101,10)

In [3]:
arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
arr.sum()

550